#static, dynamic and json

dynamic-benchmark:
	time php -f php-client.php dynamic

json-benchmark:
	time php -f php-client.php json

static-benchmark:
	time php -f php-client.php static


#rest - php client/php server

rest-benchmark:
	time php -f php-client.php rest
